Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp-education/ubuntu-24-04"
  config.vm.box_version = "0.1.0"


  ###################################
  ### Virtual machine settings
  ###################################

  # Configuration of virtualbox provider
  config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = "2"
        vb.name = "my-docker-vm"
    end


  ###################################
  ### Host settings
  ###################################
  
  # Set hostname
  config.vm.hostname = "my-docker-vm"

  # Vagrant SSH connection settings
  # Prevent Vagrant from replacing the default SSH key with a unique newly generated key
  # VERY UNSECURE - only use for testing/development environments
  # config.ssh.insert_key = false

  # Disable automatic update of virtual box guest editions
  config.vbguest.auto_update = false

  # Network settings
  config.vm.network "public_network", ip: "192.168.50.10", bridge: "Realtek 8822CE Wireless LAN 802.11ac PCI-E NIC", hostname: true
  #config.vm.network "forwarded_port", guest: "8081", host: "8081"

  # Sync folders
  # Disable default vagrant folder sync
  config.vm.synced_folder ".", "/vagrant", disabled: true
  
  # Create a dedicated mount point for transfer files
  # config.vm.synced_folder "/mnt/c/Users/<user>/Documents/Vagrant/project", "/home/vagrant/project", create: true


  ###################################
  ### Ansible installation
  ###################################

  # Install Ansible in the VM
  config.vm.provision "shell", inline: "apt-get update && apt-get install -y ansible"

  ##################################
  ### Execute provisioning script
  ###################################

  config.vm.provision "shell", name: "add-user-script",
    path: "../transfer/add-user.sh",
    args: "ansible",
    privileged: true
  
  config.vm.provision "file",
    source: "../transfer/uploaded_key.pub",
    destination: "/tmp/uploaded_key.pub"
  
  # Run the provision script from the transfer directory
  config.vm.provision "shell", name: "add-ssh-key-script",
    path: "../transfer/add-ssh-authorized-key.sh",
    args: ["ansible", "/tmp/uploaded_key.pub"],
    privileged: true
end