Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp-education/ubuntu-24-04"
  config.vm.box_version = "0.1.0"

  # Define the user whose home directory to use
  vm_user = "ubuntu"
  home_dir = "/home/#{vm_user}"


  ###################################
  ### Virtual machine settings
  ###################################

  # Configuration of virtualbox provider
  config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = "2"
        vb.name = "my-docker-vm"
    end

  # When started from WSL: Prevent mapping of folders
  config.vm.synced_folder ".", "/vagrant", disabled: true

  ###################################
  ### Host settings
  ###################################
  
  # Set hostname
  config.vm.hostname = "my-docker-vm"

  # Vagrant SSH connection settings
  # Prevent Vagrant from replacing the default SSH key with a unique newly generated key
  # VERY UNSECURE - only use for testing/development environments
  # config.ssh.insert_key = false

  # Disable automatic update of virtual box guest editions
  config.vbguest.auto_update = false

  # Network settings
  config.vm.network "public_network", ip: "192.168.50.10", bridge: "Realtek 8822CE Wireless LAN 802.11ac PCI-E NIC", hostname: true
  config.vm.network "forwarded_port", guest: "8081", host: "8081"

  # Sync project folder
  config.vm.synced_folder "/mnt/c/Users/morad/Documents/Vagrant/project", "/home/ubuntu/project", create: true

  ###################################
  ### Ansible Provisioning
  ###################################

  # Install Ansible in the VM
  config.vm.provision "shell", inline: "apt-get update && apt-get install -y ansible"

  # Run Ansible Playbook for all configuration
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "ansible/playbook.yml"
    ansible.become = true
  end
end
