Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp-education/ubuntu-24-04"
  config.vm.box_version = "0.1.0"

  # Define the user whose home directory to use
  vm_user = "vagrant"
  home_dir = "/home/#{vm_user}"

  # Configuration of virtualbox provider
  config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = "2"
        vb.name = "my-docker-vm"
    end

  # Set hostname
  config.vm.hostname = "my-docker-vm"
  
  # Disable automatic update of virtual box guest editions
  config.vbguest.auto_update = false

  # Network settings
  config.vm.network "public_network", ip: "192.168.50.10", bridge: "Realtek 8822CE Wireless LAN 802.11ac PCI-E NIC", hostname: true
  config.vm.network "forwarded_port", guest: "8081", host: "8081"

  # When started from WSL: Prevent mapping of folders
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "/mnt/c/Users/morad/Documents/Vagrant/project", "/home/vagrant/project", create: true

  # SSH settings
  # Prevent Vagrant from replacing the default SSH key with a unique newly generated key
  # VERY UNSECURE - only use for testing/development environments
  # config.ssh.insert_key = false
  # Uploading my SSH public key
  config.vm.provision "file", source: "~/.ssh/ansible_demo.pub", destination: "~/.ssh/uploaded_key.pub"
  config.vm.provision "shell", path: "../../scripts/add-ssh-authorized-key.sh", args: [vm_user]

  # Set timezone and keyboard layout using external script
  config.vm.provision "shell", name: "set-timezone-and-keyboard", path: "../../scripts/set-german-timezone-and-keyboard-layout.sh"

  # Install Docker and dependencies
  config.vm.provision "shell", name: "install-docker", path: "../../scripts/install-docker.sh", args: [vm_user]

  # Run Ansible Playbook
  #config.vm.provision :shell, inline: "apt-get update"
  #config.vm.provision :shell, inline: "apt-get install -y ansible"
  #config.vm.provision "ansible" do |ansible|
  #      ansible.playbook = "playbook.yaml"
  #  end
end
